### ISSUE TITLE
Apache license violation and original copyright omission

### ISSUE THREAD

**Issue by JakeWharton** [permissions-dispatcher/kompile-testing#11]
The file https://github.com/permissions-dispatcher/kompile-testing/blob/master/src/main/java/kompile/testing/Compiler.kt is derived from https://github.com/square/moshi/blob/master/kotlin/codegen/src/test/java/com/squareup/moshi/kotlin/codegen/KotlinCompilerCall.kt but does not retain the copyright designation and license information in the derived work. In order to use this code, you must comply with item 4 of the Apache license (the license of the original work).

**Comment by hotchemi** [comment]
ooh thank you let us address 🙇

**Comment by hotchemi** [comment]
I've added copyright with referring to https://opensource.stackexchange.com/q/7300. Sorry for our bad and thank you for your heads up🙇

**Comment by JakeWharton** [comment]
Thank you!
